# **ÖDEV-2**

1-Numpy kütüphanesini import edin.

In [2]:
import numpy as np

2-1'den 5 e kadar (5 dahil) b isimli bir dizi oluşturun.

In [3]:
b= np.arange(6)
b

array([0, 1, 2, 3, 4, 5])

3- 20 adet 0'dan oluşan 4 x 5' lik dizi oluşturun.

In [10]:
np.zeros((4,5),dtype=int)


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

4- 15 adet 7 sayısından oluşan diziyi 3x5 olarak yazın.

In [9]:
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

5- 10–70 e kadar 5 er artan sayıları yaz.

In [14]:
np.arange(10,70,5)


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

6- 10–20 arasında 15 aynı uzaklıkta elemanı olan array oluşturun. (linspace metodunu kullanın.)

In [15]:
np.linspace(10,20,num=15)

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

7- Rastgele sayılardan oluşan diziyi 3x5 boyutunda yazdır.

In [24]:
np.random.rand(3,5)

array([[0.46105629, 0.70690855, 0.51185357, 0.39899662, 0.26443168],
       [0.03370298, 0.29885389, 0.80905237, 0.81814682, 0.02547928],
       [0.61736255, 0.15193105, 0.16023748, 0.95516073, 0.81071275]])

8- 5 elemanlı birim matris oluşturun. eye() metodu kullanın.

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9- 0'dan 24 e kadar array oluştur. Sonra reshape metodu ile 4x6 boyutu olarak yazın.

In [31]:
np.arange(0,24).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

10- 0 ile 1 arasında rastgele 10 sayıdan oluşan bir array tanımlayın. Minimum ve maksimum değerleri bulun.

In [39]:
a=np.random.rand(1,10)
a


array([[0.97471685, 0.77598031, 0.17322888, 0.03648223, 0.96784041,
        0.12686898, 0.95538351, 0.18966417, 0.5333748 , 0.22073787]])

In [46]:
np.min(a)


0.03648223399835904

In [47]:
np.max(a)

0.9747168490628961

11- 36 sayıdan oluşan rastgele sayılar 6x6' lık array olarak yazdırın.

In [7]:
x=np.random.randint(0,36,(6,6))
x

array([[ 6, 18,  4, 18,  6,  6],
       [30, 28, 32, 16, 31, 10],
       [ 2, 17, 24, 17,  2,  7],
       [17,  4, 17,  4, 26, 29],
       [20, 30, 26,  7, 13, 11],
       [27, 23, 31, 13, 34, 10]])

12- 5.satırdaki elemanları gösteriniz.

In [8]:
x[4,:]

array([20, 30, 26,  7, 13, 11])

13- 6.satır ve 6.sutundaki elemanları gösteriniz.

In [10]:
x[5,:]

array([27, 23, 31, 13, 34, 10])

In [11]:
x[:,5]

array([ 6, 10,  7, 29, 11, 10])

14-4.sutundaki tüm elemanları çekin.

In [12]:
x[:,3]

array([18, 16, 17,  4,  7, 13])

15- For döngüsünü ve flat metodunu kullanarak satır satır elemanları yazdırınız.

In [81]:
new_list=[]
for i in x:
    x.flat[6]
    new_list.append(i)
    
new_list    

[array([23,  1, 29,  9, 24, 18]),
 array([25, 23, 18, 12, 13, 12]),
 array([12,  5, 15,  2,  1, 13]),
 array([34, 14, 33,  9,  4, 28]),
 array([11,  0, 18, 22, 10,  8]),
 array([28,  7, 24, 18, 13, 15])]

16- 0 ile 1 aralığında bir array oluştur. Bu array değerini 5 ile çarpın.

In [94]:
x = np.array([0.2,0.4,0.6,0.8])
b=x*2
b

array([0.4, 0.8, 1.2, 1.6])

16- Satırların toplam değeri nedir?

In [95]:
b.sum()

4.0

17-Satırların standart sapma değeri nedir?

In [96]:
b.std()

0.4472135954999579

18-Satırların varyans değeri nedir?

In [97]:
b.var()

0.2

19- Satırların transpoz değeri nedir?

In [99]:
b.transpose()

array([0.4, 0.8, 1.2, 1.6])